config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  get 'home/about'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-2">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="form-group mb-2">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="form-group mb-2">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="form-group mb-2">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="form-group mb-2">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div >
    <%= form.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">    


<div class="card text-center">
  <div class="card-header">
    <h1><%= friend.first_name %> <%= friend.last_name %></h1>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= friend.phone %></h5>
    <p class="card-text"><%= friend.email %>  |  <%= friend.twitter %> </p>
    <%= button_to "Destroy this friend", @friend, method: :delete,  class:'btn btn-danger ' %>
  </div>
  <div class="card-footer text-body-secondary">
   <%= link_to "Edit this friend", edit_friend_path(@friend), class:'btn btn-info'  %>
  <%= link_to "Back to friends", friends_path, class:'btn btn-secondary' %>
    </div>
</div>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Details", @friend, class:'btn btn-info' %> 
  <%= link_to "Back to friends", friends_path, class:'btn btn-secondary' %>
</div>

app/views/friends/index.html.erb
<h1>Friends List</h1>


<div id="friends">

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @friends.each do |friend,| %>
    <tr>
      <th scope="row"><%= friend.id%></th>
      <td><%= friend.first_name %></td>
      <td><%= friend.last_name %></td>
      <td><%= friend.email %></td>
      <td> <%= friend.phone %></td>
      <td><%= friend.twitter %></td>
      <td><%= link_to "Details", friend %>
       </td>
    </tr>
      <% end %>
    </tbody>
</table>
</div>

<%= link_to "New friend", new_friend_path, class:'btn btn-primary' %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class:'btn btn-secondary' %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>


<div>
  
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark" data-bs-theme="dark" >
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class: "navbar-brand"  %>
    <%# <a class="navbar-brand" href="#">Friends App</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
            <%= link_to 'Friends', friends_path, class: "nav-link" %>
        </li>
              <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
            <%= link_to 'Login In', new_user_session_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
        </li>
         <li class="nav-item">
            <%= link_to 'Profile', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'About Us', home_about_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About page <h1>

app/views/home/index.html.erb
<h1> Home page <h1>

app/views/layouts/_notification.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>
    <%= render '/home/header'%>
    <div class= "container" >
    <br/>
    <% if notice %>
    <%= render "layouts/notification"%>
    <%end%>
    <%= yield %>
    </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>